---
## The following section is a hack to get this role running in docker containers
- hosts: all
  become: false
  tasks:
# following requires ansible v2.2:
  - name: "Create a custom bridge network (to ensure dns/autodiscovery for our docker cluster)"
    docker_network:
      name: "isolated_nw"
    delegate_to: localhost
    run_once: yes

- hosts: all
  become: True
  vars:
      hostgroup: 'all'   # Which group in the ansible inventory should be considered
      ipaddrnr: 0
      hosts_file: /etc/hosts
  tasks:
  - name: Install netstat for unit tests
    apt: name=net-tools state=present

## End of docker hack
- hosts: all
  become: True
  roles:
  - role: "lhoss.java"

- hosts: zookeeper_hosts
  become: True
  roles:
  - { role: "teralytics.zookeeper" }

- hosts: hadoop_hosts
  become: True
  roles:
  - ansible-hdfs
  serial: "{{serial|default(0)}}"
