---
## The following section is a hack to get this role running in docker containers

- hosts: all
  become: True
  vars:
      hostgroup: 'all'   # Which group in the ansible inventory should be considered
      ipaddrnr: 0
      hosts_file: /etc/hosts
  tasks:
  - name: Install dnsmasq
    apt: name=dnsmasq state=present
  - name: Overwrite nameserver in /etc/resolv.conf
    shell: bash -c "echo 'nameserver 127.0.0.1' > /etc/resolv.conf"
  - name: Generate /etc/hosts from group '{{ hostgroup }}'
    template: src=hosts.j2 dest=/tmp/hosts owner=root group=root mode=0644 backup=yes
  - name: Add /tmp/hosts to dnsmasq.conf
    lineinfile: dest=/etc/dnsmasq.conf regexp='^addn-hosts=' line='addn-hosts=/tmp/hosts'
  - name: Add server 8.8.8.8 to dnsmasq.conf
    lineinfile: dest=/etc/dnsmasq.conf regexp='^server=8.8.8.8' line='server=8.8.8.8'
  - name: Restart dnsmasq
    service: name=dnsmasq state=restarted
  - name: Install software-properties-common as 'add-apt-repository' is not present in docker container
    apt: name=software-properties-common state=present

### End of docker hack

- hosts: all
  become: True
  pre_tasks:
  - shell: echo | add-apt-repository ppa:openjdk-r/ppa # echo puts an implicit newline which is needed
    when: ansible_os_family == "Debian"
  roles:
    - {role: "JasonGiedymin.java", when: ansible_os_family == "Debian"}

- hosts: zookeeper_hosts
  become: True
  roles:
  - { role: "teralytics.zookeeper" }

- hosts: hadoop_hosts
  become: True
  roles:
  - ansible-hdfs
  serial: "{{serial|default(0)}}"
