## OpenJDK Java
#- name: JasonGiedymin.java
#  src: JasonGiedymin.java

# TODO switch to upstream role if/once my latest feature gets merged:
#- name: geerlingguy.java
#  src: git+https://github.com/geerlingguy/ansible-role-java
#  version: tags/1.7.2
- name: lhoss.java
  src: git+https://github.com/lhoss/ansible-role-java
  version: remotes/origin/support_configurable_ppa_repositories_per_distro

## Zookeeper
- src: git+https://github.com/teralytics/ansible-zookeeper
  name: teralytics.zookeeper
  version: tags/0.17.0
